name: Leonardo Tamburri
favicon: null
layout_spectrum: 0.74889
typography_spectrum: 0.37785
title: "Hi i'm Leo"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d1011'
    - '#f1f5f6'
    - '#6e8182'
    - '#8ea2a1'
    - '#b2c2c1'
  brandStrength: 1
  lightness: 1
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
