typography_spectrum: 0.37785
color:
  brandColors:
    - '#0d1011'
    - '#f1f5f6'
    - '#6e8182'
    - '#8ea2a1'
    - '#b2c2c1'
  brandStrength: 1
  lightness: 1
  saturation: 0.5625
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74889
analytics:
  google: null
  facebook: null
  twitter: null
name: Leonardo Tamburri
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Hi i'm Leo
description: Creative Director
purpose: []
