name: Leonardo Tamburri
favicon: null
layout_spectrum: 0.8622412148397416
typography_spectrum: 0.7263788564596325
title: "Hi i'm Leo"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.0922673624008894
  lightness: 0.9715515098068863
  saturation: 0.019233799539506435
  rhythmicContrast: 0.5889472719281912
purpose: []
