name: Leonardo Tamburri
favicon: null
layout_spectrum: 0.26885
typography_spectrum: 0.37785
title: "Hi i'm Leo"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#828a98'
    - '#d9dadf'
    - '#000000'
    - '#393c49'
    - '#5d616a'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
